# Generated by Django 3.2.7 on 2021-09-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='movement',
            field=models.CharField(default='modern', max_length=100),
            preserve_default=False,
        ),
    ]
