# Generated by Django 3.2.7 on 2021-09-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_message_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
    ]
