# Generated by Django 3.2.7 on 2021-09-15 15:56

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_alter_message_isread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='isRead',
            field=models.BooleanField(blank=True, verbose_name=django.db.models.fields.NullBooleanField),
        ),
    ]
