# Generated by Django 3.2.7 on 2021-09-15 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0014_alter_message_isread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='isRead',
            new_name='is_read',
        ),
    ]
